// Code generated by MockGen. DO NOT EDIT.
// Source: internal/collector/github/query.go

// Package mocks is a generated GoMock package.
package github

import (
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	githubv4 "github.com/shurcooL/githubv4"
)

// MockQuery is a mock of Query interface.
type MockQuery struct {
	ctrl     *gomock.Controller
	recorder *MockQueryMockRecorder
}

// MockQueryMockRecorder is the mock recorder for MockQuery.
type MockQueryMockRecorder struct {
	mock *MockQuery
}

// NewMockQuery creates a new mock instance.
func NewMockQuery(ctrl *gomock.Controller) *MockQuery {
	mock := &MockQuery{ctrl: ctrl}
	mock.recorder = &MockQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuery) EXPECT() *MockQueryMockRecorder {
	return m.recorder
}

// QueryBasicRepoData mocks base method.
func (m *MockQuery) QueryBasicRepoData(ctx context.Context, client *githubv4.Client, u *url.URL) (*BasicRepoData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryBasicRepoData", ctx, client, u)
	ret0, _ := ret[0].(*BasicRepoData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryBasicRepoData indicates an expected call of QueryBasicRepoData.
func (mr *MockQueryMockRecorder) QueryBasicRepoData(ctx, client, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryBasicRepoData", reflect.TypeOf((*MockQuery)(nil).QueryBasicRepoData), ctx, client, u)
}
